# Generated by Django 5.0.1 on 2024-12-05 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Manga',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('title', models.CharField(default='manga title', max_length=200)),
                ('description', models.TextField(default='description')),
                ('original_language', models.CharField(default='japanese', max_length=50)),
                ('last_volume', models.CharField(blank=True, max_length=50, null=True)),
                ('last_chapter', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(blank=True, max_length=50)),
                ('year', models.IntegerField(blank=True)),
                ('grade', models.FloatField(blank=True)),
                ('url_cover', models.URLField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, default=6.99, max_digits=10)),
                ('stock', models.IntegerField(default=0)),
            ],
        ),
    ]
